README.rst

Hi, This fixes some phrasing and replaces 'criticity' with 'criteria' though I'm not sure if that was the intent. I also uses all caps for `ASSETMAP/VOLINDEX`.

README.rst - fixes some phrasing

---

clairmeta/dcp_check_sign.py

I don't think <Signature> nodes are required to have a namespace, do you agree?  If so, this patch fixes digest comparison for files with no namespace in<Signature>.

Allow <Signature> nodes without namespaces.

---

clairmeta/dcp_check_pkl.py
clairmeta/dcp_check_subtitle.py
clairmeta/dcp_check_utils.py
clairmeta/settings.py

The results of these checks depends on the platform and might not be relevant at all, better check the actual content.

Remove Mime type based checks

---

clairmeta/dcp_check_sign.py
clairmeta/dcp_check_vol.py
clairmeta/utils/xml.py
clairmeta/xsd/DCSubtitle.xsd

*  Digital signature fail for XML without prefixes
*  Interop VOLINDEX schema check fail
*  DCSubtitles schema check fail for ReelNumber with text

Fix some DCP check issues

---

Pipfile.lock
clairmeta/dcp_check_subtitle.py

Subtitle UUID check was not correct.
Interop :
*  XML DCSubtitle/SubtitleID should match the CPL MainSubtitle/Id
*  XML subfolder name should contain MainSubtitle/Id
SMPTE :
*  XML SubtitleReel/Id should match the MXF ResourceId, here we rely on the fact that asdcp-info parser (As_02_TimedText parser) store the TimedTextDescriptor/ResourceID (from SMPTE 429-5) in a global AssetID key.

Fix/subtitle UUID

---

clairmeta/dcp.py

Crash on parsing DCP with empty XML files :
> \<?xml version="1.0" encoding="UTF-8" standalone="no"?>

Fix crash for empty xml files

---

.travis/Dockerfile-build-artful
.travis/Dockerfile-build-bionic
.travis/Dockerfile-install-artful
.travis/Dockerfile-install-bionic
.travis/build_env.sh
README.rst

Ubuntu 17.04 artful [is end of file]( http://fridge.ubuntu.com/2018/07/19/ubuntu-17-10-artful-aardvark-end-of-life-reached-on-july-19-2018/), switching to [18.04 bionic](https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes).
Or should we keep the artful variant, for now, so we don't break anything for current users?

Add apt support for Ubuntu 18.04 bionic and dropping 17.04 artful

---

clairmeta/dcp_check_subtitle.py

I have a Interop subtitle XML with this line:
``<Subtitle SpotNumber="1" FadeUpTime="20" FadeDownTime="20" TimeIn="00:00:00:000" TimeOut="00:00:00:010">``
Before this patch I get the error "Subtitle 1 null or negative duration" from check_subtitle_cpl_st_timing(). This is because the duration is rounded to 0 by floor division in ticks_to_frame().
10 ticks at 24 fps evaluates to 0.96 frames in floating point. Since a subtitle can not be displayed for a fraction of a frame it makes sense to always round up to the next whole frame.

Use the ceiling of frame fractions when converting subtitle time code to frames.

---

clairmeta/dcp_check_sign.py

This check for correct field type of the Dn, O, OU, CN attributes of certificate Issuer and Subject fields.
I had to use a private type _ASN1Type of the cryptography module to get the actual encoding of these attributes. If anyone know a better way to do this I would be grateful.

X509 subject and issuer attribute encoding check

---

clairmeta/dcp_check_isdcf_dcnc.py

Bypass naming convention versus. essence check for burned subtitles

---

clairmeta/dcp_check_subtitle.py

Not required in SMPTE DCP
XSD will detect if tag is missing for Interop
@cth103

Early exit if Language tag is not found

---

.gitignore
Pipfile
clairmeta/sequence.py
clairmeta/sequence_check.py
clairmeta/utils/file.py
clairmeta/utils/probe.py

File sequence probe now only store [start, end] index and count of elements instead of file path list.
Fix #77

File sequence scan improvements

---

CONTRIBUTORS
README.rst
clairmeta/dcp.py
clairmeta/dcp_check.py
tests/test_cli.py

In this Pull Request :
*  Fix a minor typo in the Readme code samples.
*  Improve consistence for asset path metadata in the CompositionPlaylist/ReelList/Assets dictionary.
`Path` is the relative path available for internal assets and empty for external assets, `AbsolutePath` is the absolute path available for internal assets and for external assets (only if a `dcp.check(ov_path="/my/ov")` is performed, see below)
```
from clairmeta import DCP
dcp = DCP("/my/dcp/version_file")
dcp.check(ov_path="/my/dcp/original_version")
metadata = dcp.parse()
```

Improve assets path metadata consistency

---

clairmeta/dcp_check_atmos.py
clairmeta/dcp_check_cpl.py
clairmeta/dcp_check_subtitle.py
clairmeta/dcp_check_utils.py
clairmeta/profile.py

Ignore various UUID / UL case mismatch :
*  Subtitle / Folder (for Interop) vs. CPL UUID comparison. 
Previously we returned an error in this case, now only a warning.
*  Atmos Essence Coding UL, CPL / MXF comparison
Silently succeed
Feedback much welcome on this subject !

UUID case insensitive checks

---

clairmeta/dcp.py

@benjamingymg 
Fix inconsistent file ordering between different platforms when using `os.walk()` (eg. MacOS gets ordered files but not Linux).

Make sure file order is consistent

---

clairmeta/dcp_check_base.py

This allow incomplete check name in the profile bypass section to quickly filters out multiple checks.

Allow filtering check with incomplete names

---

clairmeta/dcp_check_subtitle.py

Fix crash in the subtitle parser, related to #131

Fix subtitle fade time parser for 0 duration

---

clairmeta/dcp_check_subtitle.py

Explicitly check for empty LoadFont ID attribute on SMPTE DCP

---

.codecov.yml
clairmeta/sequence.py
clairmeta/utils/probe.py

Hey @nikicpetar,
I propose this update, that is basically moving your fix to the probe module. I did this because there is already code that deals with difference in mediainfo output depending on the version. I feel it's easier to manage this way.
Does that feel right to you ? I test on ubuntu 18.04 and mediainfo 0.7.62 and it seemed alright but I'll wait for your approval.
Note that I did the `split()` thing because on my test, mediainfo was actually returning `16 bits / 16 bits / 16 bits` !

Fix mediainfo bitdepth

---

clairmeta/dcp_check_subtitle.py
clairmeta/dcp_parse.py

This pull request address issues reported in #155, specifically 2 DCPs reported by @jamiegau were tested.
EDCF-SMPTE-Bv2_TST_S_EN-EN_OV_51-HI-VI-Atmos_2K_20161020_DTU_SMPTE_OV
*  Subtitle's Text and Font elements hierarchy were making the font check crash, this should be fixed
*  Note that this DCP is still considered not valid by ClairMeta
*  IntrinsicDuration does not match between CPL and MXF for the subtitles assets
*  Leaf Certificate for digital signature missing the ContentSigner role
*  Atmos essence coding UL inside the CPL contains an extra dot ( 060e2b34.0401.0105.0e090604.00000000 instead of 060e2b34.04010105.0e090604.00000000)
FMSC-Ad-June_ADV_F_2K_20180604_SMPTE_OV
*  This package will remain considered as broken by ClairMeta because the CPL only Reel contains two MainSound …

Minor fixes to probe / check

---

clairmeta/dcp_check.py
clairmeta/dcp_check_am.py
clairmeta/dcp_check_atmos.py
clairmeta/dcp_check_base.py
clairmeta/dcp_check_cpl.py
clairmeta/dcp_check_isdcf_dcnc.py
clairmeta/dcp_check_picture.py
clairmeta/dcp_check_pkl.py
clairmeta/dcp_check_sign.py
clairmeta/dcp_check_sound.py
clairmeta/dcp_check_subtitle.py
clairmeta/dcp_check_vol.py
tests/test_cli.py

This is a first attempt to improve the built-in ClairMeta check report:
* Messages are now grouped by offending assets
* Report contains check description
* Display ContentTitleText / AnnotationText for CPL / PKL
There is still some work to make sure we export all relevant data for 3rd party report generation.

Improve console report formating

---

README.rst
clairmeta/cli.py
clairmeta/dcp_check.py
clairmeta/dcp_check_subtitle.py
clairmeta/utils/file.py

Example usage, using 3 different ways:
```
from clairmeta import DCP
from clairmeta.utils.file import ConsoleProgress
class MyProgress(ConsoleProgress):
def __init__(self, my_setting_1, my_setting_2):
super(MyProgress, self).__init__()
self.my_setting_1 = my_setting_1
self.my_setting_2 = my_setting_2
def __call__(self, file_path, file_processed, file_size, file_elapsed):
super(MyProgress, self).__call__(file_path, file_processed, file_size, file_elapsed)
print(self.my_setting_1, self.my_setting_2)
def function_callback(file_path, file_processed, file_size, file_elapsed):
print(file_path, file_processed, file_size, file_elapsed)
dcp = DCP("tests/resources/DCP/ECL-SET/ECL01-SINGLE-CPL_TST_S_EN-XX_UK-U_71_2K_DI_20171218_ECL_IOP_OV")
status, report = dcp.check(hash_callback=function_callback) …
```

Improve console progress report user extensibility

---

clairmeta/cli.py
clairmeta/dcp_check_base.py
clairmeta/dcp_check_report.py
tests/test_cli.py

This is a quick stab at implementing a format settings for the DCP check report, trying to get similar functionality we currently have for the probe report.

Support for DCP check report dict-json-xml formats

---

clairmeta/dcp_check.py
clairmeta/dcp_check_am.py
clairmeta/dcp_check_atmos.py
clairmeta/dcp_check_base.py
clairmeta/dcp_check_cpl.py
clairmeta/dcp_check_execution.py
clairmeta/dcp_check_isdcf_dcnc.py
clairmeta/dcp_check_picture.py
clairmeta/dcp_check_pkl.py
clairmeta/dcp_check_report.py
clairmeta/dcp_check_sign.py
clairmeta/dcp_check_sound.py
clairmeta/dcp_check_subtitle.py
clairmeta/dcp_check_utils.py
clairmeta/dcp_check_vol.py
clairmeta/profile.py
tests/test_dcp_check.py

This PR implement a new way of handling errors within checks, hopefully enabling simpler implementation and flexibility.
*  Error are simply appended to an internal error list (get reset'ed between each check execution)
*  Error can specify a custom name and documentation, this allow per-error control of report error level. Existing tests that returns multiple errors may or may not tag the errors, this should probably not be mandatory and can be added on a per case basis if we need the extra flexibility. The current PR added such tag for some checks but that's somewhat arbitrary.
*  Fatal error can be used to mimic the previous behaviour
Remaining tasks:

Refactor check error handling

---

clairmeta/dcp_check_picture.py

This address issue #180, please see included comment for more details.
Deeper J2K codestream validation is needed as stated in #10, this should probably rely on an external tool. The simpler solution here seems to just ignore the check when we don't have the required MXF descriptor, and hopefully include more tests in the future. Please let me know if you don't agree with that.

Ignore undetected picture decomposition levels

---

clairmeta/dcp_check_utils.py

Python `open()` use locale dependent encoding and on Windows it can still default on restricted character set, this was missed here.

Use explicit utf-8 decoding on Windows

---

clairmeta/dcp.py
clairmeta/dcp_check.py
clairmeta/dcp_check_global.py
clairmeta/profile.py
clairmeta/settings.py

Even though I understand that DCP standards recommend no foreign file, for archival purposes, checksum files (eg: MD5 file) could be in the same folder as the DCP files and excluding certain files could be practical to still do the check of other foreign files.
This pull request is a very simple implementation that relies on a new setting in DCP_CHECK_SETTINGS.

Prototyping a file exception list for DCP check. File list in settings.py

---

clairmeta/dcp_check_global.py

As the title says, this new logic allows using regular expressions to allow foreign files, for example to allow all .md5 files.

Adapting the allowed_foreign_files logic to use regular expressions

---

clairmeta/dcp_check_execution.py
clairmeta/dcp_check_global.py
clairmeta/profile.py
clairmeta/report.py
tests/test_dcp_check.py

This PR contains the following changes:
- Naming convention check now default to INFO instead WARNING following discussion in #235 
- Improve description and error reporting from `check_dcp_signed` as reported by @jamiegau 
- Make sure errors reported in the console output are always ordered from most to least severe

Improve check diagnostic message and lower naming convention error level

---

clairmeta/dcp_check_sign.py
clairmeta/profile.py

From DCI Specifications 1.4.4:
> The CPL meets the two validation requirements defined in Section 5.2.1. of SMPTE 430-5 "D-Cinema Operations – Security Log Event Class and Constraints for D-Cinema" with the following caveat: When performing Step 9 of Section 6.2 in SMPTE ST 430-2, the desired time of the validation context shall be equal to the IssueDate field of the target CPL (and not the current time). This behavior permits the continued playback of a CPL after the expiration of its signing certificate, but ensures that the signing took place during the certificate's validity period.

Validate certificate date against the IssueDate instead of current time
