Ymagis/ClairMeta

clairmeta/cli.py
tests/test_cli.py

Command line interface now returns proper error codes

---

clairmeta/dcp_check.py
clairmeta/dcp_check_isdcf_dcnc.py
clairmeta/dcp_parse.py
clairmeta/utils/isdcf.py

*  Check for digital signature in case of encrypted SMPTE DCP as this may cause failure to ingest.
*  Support EclairColor ISDCF content type modifier

New minors checks

---

clairmeta/xsd/DCSubtitle.xsd

Misc. fixes. Please consider merging.

Dcsubtitle.xsd: various improvements

---

README.rst

Salut Rémi,
Je viens de commencer ma formation ^^
Je fais juste un mini exo pour neuneu consistant à se servir de git et github et j'ai modifié le readme avec 3 conneries inutiles histoire de te faire un clin d'oeil ;-)
A plus !

url to help find standards added

---

clairmeta/utils/uuid.py

Allow uppercase in UUIDs

---

README.rst
clairmeta/dcp_check.py
clairmeta/dcp_check_am.py
clairmeta/dcp_check_subtitle.py
clairmeta/profile.py

This PR include :
*  Remove profile log level setting
*  Add a new check based on VolIndex deprecation (suggested by @matmat)
*  Case insensitive subtitles extension check (suggested by @matmat)

Check various fix

---

clairmeta/dcp_check_subtitle.py

LoadFont element is mandatory for SMPTE subtitles

---

clairmeta/dcp_parse.py

Total assets size for AssetMap and each PKLs available in probe

---

clairmeta/dcp_check_atmos.py
clairmeta/profile.py

Update Atmos fields error level.

Atmos max channels and objects count will be optional

---

.travis.yml

This enable the whole range of ClairMeta unit tests using [ClairMeta Data](https://github.com/Ymagis/ClairMeta_Data).

Run unit tests using ClairMeta Data

---

clairmeta/dcp_check_sign.py

Better error messages in case of invalid role(s) found in signing certificates.

Improve certificate role check diagnostic

---

.gitignore
tests/README.rst

Describe how to get test materials

---

README.rst
clairmeta/dcp_parse.py
clairmeta/settings.py
clairmeta/xsd/PROTO-ASDCP-CC_CPL_20070926.xsd
clairmeta/xsd/catalog.xml

tests weren't run from the repo due to lack of tests' resources
relates to https://github.com/Ymagis/ClairMeta/issues/110

add `MainClosedCaption` element from `http://www.digicine.com/PROTO-ASDCP-CC-CPL-20070926#` namespace

---

clairmeta/dcp_check_isdcf_dcnc.py

These messages meaning were potentially inverted.

Fix some error messages related to ContentTitle checks

---

clairmeta/sequence_check.py
clairmeta/settings.py

Implement custom size tolerance

---

.travis.yml

Refactoring Travis YAML

---

clairmeta/cli.py
clairmeta/dcp_check_base.py
clairmeta/dcp_check_cpl.py

Fix unicode raised exception for py2 (dcp_check_cpl)

---

clairmeta/dcp_check.py
clairmeta/dcp_check_am.py
clairmeta/dcp_check_atmos.py
clairmeta/dcp_check_cpl.py
clairmeta/dcp_check_picture.py
clairmeta/dcp_check_pkl.py
clairmeta/dcp_check_sign.py
clairmeta/dcp_check_sound.py
clairmeta/dcp_check_subtitle.py
clairmeta/dcp_check_vol.py

Where applicable, reference the standard / document behind the check being performed.
This is still a work in progress...

Reference standard for every check performed

---

clairmeta/dcp_check_isdcf_dcnc.py
clairmeta/utils/isdcf.py

Address some feedback from #151 and #152

Improvements to Digital Naming Convention checks

---

README.rst
clairmeta/cli.py
clairmeta/dcp_check.py
clairmeta/dcp_check_pkl.py
clairmeta/utils/file.py

This update will add total progress of reading all files when verifying hash on a DCP.

added total progress to -progress ouput

---

clairmeta/dcp.py
clairmeta/dcp_check.py
clairmeta/dcp_check_am.py
clairmeta/dcp_check_atmos.py
clairmeta/dcp_check_base.py
clairmeta/dcp_check_cpl.py
clairmeta/dcp_check_isdcf_dcnc.py
clairmeta/dcp_check_picture.py
clairmeta/dcp_check_pkl.py
clairmeta/dcp_check_report.py
clairmeta/dcp_check_sign.py
clairmeta/dcp_check_sound.py
clairmeta/dcp_check_subtitle.py
clairmeta/dcp_check_utils.py
clairmeta/dcp_check_vol.py
clairmeta/dcp_parse.py
clairmeta/dcp_utils.py
tests/test_dcp_check.py

This pull request is a **work in progress** with the following update:
*  New DCP `CheckReport` object with more informations returned by the API (built-in console report is the first user)
*  Probe CompositionPlaylist global key indicating the presence of CompositionMetadataAsset
*  Starting to replace built-in Python Exception by our own custom type (so that client code can differentiate known errors and bugs)

Report public API improvement and various fixes

---

clairmeta/dcp_parse.py

Fix handling of marker list consisting of 1 item

---

clairmeta/dcp.py
clairmeta/dcp_parse.py

Note that this will fail test at the moment due to the new probe key added.

Probe actual on disk asset total size

---

clairmeta/dcp_check_am.py
clairmeta/profile.py

Lower AssetMap empty fields check to info level

---

clairmeta/utils/file.py
scripts/dcp_copy.py

A sample usage to perform DCP copy.

Sample dcp copy script

---

clairmeta/dcp_check_subtitle.py
clairmeta/dcp_utils.py

New PR because I messed up my branches, sorry!

Add check for TimeIn < 4 seconds of CPL's first subtitle asset. (new PR)

---

.gitignore
README.rst
clairmeta/dcp.py
clairmeta/profile.py
tests/test_dcp_check.py

As can be seen in the discussion in #208, this feature and it's design is clearly not ready for release. In the interest of pushing a new release with bug fixes and new checks, this PR revert the changes.

Revert multiple profile validation

---

clairmeta/dcp_check_sign.py
clairmeta/profile.py

Add new warning when digital signature certificates validity extends past specifics thresholds.

Add certificate date overflow check

---

.github/workflows/test-package.yml
clairmeta/dcp_parse.py

This fix an issue when parsing a CPL with markers on some reels but not all (resulting in empty MainMarkers/MarkerList elements). @jamiegau Can you please give that a go?

Fix error when parsing reels with empty MarkerList

---

clairmeta/dcp.py

Updated version of #233 from @robin-francois

Add DCP folder path analysis to probe
